### ISSUE TITLE
Flutter code is not generating

### ISSUE THREAD

**Issue by zubairehman** [roberto198907/zeplin-flutter-extended#1]
Hi, i have added this extention to my zeplin by when i click on any element it doesnt show its code. I have added tried it with other extentions for XML and react native and it works fine for them. 

**Screenshot**
<img width="800" alt="Screenshot 2019-07-09 at 8 16 50 PM" src="https://user-images.githubusercontent.com/7915601/60901052-b35c5180-a286-11e9-8e43-ed96bebb35b5.png">

**Comment by roberto198907** [comment]
Hi @zubairehman, could you go to Manage Extensions and then review if the extension is checked?

<img width="607" alt="Captura de Pantalla 2019-07-09 a la(s) 09 24 33" src="https://user-images.githubusercontent.com/48741699/60901606-79aa2d00-a22b-11e9-97f2-86a66ba65b21.png">

**Comment by zubairehman** [comment]
@roberto198907 yes it is checked

**Comment by roberto198907** [comment]
Could you send me a screen shoot @zubairehman?  The alternative could reinstall the extension, and try to add it again. I am using the extension without problems.

**Comment by roberto198907** [comment]
Could you test if the extension works for Styleguide?
<img width="1680" alt="Captura de Pantalla 2019-07-09 a la(s) 22 20 49" src="https://user-images.githubusercontent.com/48741699/60940209-e9ee9800-a297-11e9-827a-1fcfb08a41c9.png">

**Comment by zubairehman** [comment]
seems like it doesn't, please check the attached screenshot:

**Screenshot:**


![Screenshot 2019-07-10 at 11 02 04 AM (2)](https://user-images.githubusercontent.com/7915601/60944563-9b2a1800-a302-11e9-9707-d75fe0c13349.png)

**Comment by roberto198907** [comment]
it is weird because I reinstalled the extension and it is working correctly, I have friends as well using it, and they haven't reported me an unusual behavior. Could you send me your username on Zeplin to open a ticket with the Zeplin Team, they can help us to resolve your issue?

**Comment by zubairehman** [comment]
@roberto198907 i tried uninstalling all the extentions and it worked.

**Comment by roberto198907** [comment]
Great @zubairehman :) !! so I will close this issue
